name: Automatic deploy to Heroku

on:
  push:
    branches: [ main ]
    
jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Merge branches
        uses: tukasz/direct-merge-action@v2.0.2
        with:
          source-branch: main
          target-branch: heroku
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
