# This workflow will install Python dependenciese, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Cache dependencies
        id: cache-pipenv
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile') }}
      - name: Install package manager
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          if [ ! -f Pipfile.lock ]; then pipenv lock; fi
          pipenv lock -r --dev > requirements.txt
          pip install -r requirements.txt
      - name: Lint with flake8
        run: flake8 fast_home_api --max-line-length=127 --exclude 'templates'
      - name: Test with unittest
        env:
          JWT_SECRET: test-secret
        run: python -m unittest discover -s tests -t fast_home_api
