# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install pipenv
        run: |
          pipx install pipenv --python 3.9
          if [ ! -f Pipfile.lock ]; then pipenv lock; fi
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          cache: "pipenv"
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          if [ ! -f Pipfile.lock ]; then pipenv lock; fi
      - name: Install dependencies
        run: pipenv install -d --python 3.9
      - name: Lint with flake8
        run: pipenv run linter
      - name: Test with unittest
        env:
          JWT_SECRET: test-secret
        run: pipenv run test
